### ISSUE TITLE
Tolle Arbeit, ein Verbesserungsvorschlag

### ISSUE THREAD

**Issue by cgruenwied** [tobiasmiosczka/dsa5-calculator#1]
Ein Verbesserungsvorschlag zu den QS-Wahrscheinlichkeiten:
Wenn ich die Regeln richtig interpretiere, dann ist es es egal, wenn man bei einer Teilprobe unter den Zielwert würfelt. Die Fertigkeitspunkte werden nur aufgebraucht, wenn man über dem Zielwert liegt.

Als Beispiel:
FW = 10, Bonus = -2, Wurf = 10, Eigenschaft = 10 -> FW(neu) = 8
FW = 10, Bonus -2, Wurf = 5, Eigenschaft = 10 -> FW(neu) = 10

An dieser Stelle:

    let remainingFw = fw;
    if (w1 > val1 + mod) 
      remainingFw -= w1 - mod - val1;
    if (w2 > val2 + mod) 
      remainingFw -= w2 - mod - val2;
    if (w3 > val3 + mod) 
      remainingFw -= w3 - mod - val3;

Passiert aber das:
FW = 10, Bonus = -2, Wurf = 10, Eigenschaft 10 -> FW(neu) = 8 (ok)
FW = 10, Bonus -2, Wurf = 5, Eigenschaft 10 -> FW(neu) = 13 (der vermutete Fehler)

Fix-Vorschlag: Nur bei positivem Ergebnis von wx - mod - valx das Ergebnis abziehen.

Beste Grüße,

Christian

**Comment by tobiasmiosczka** [comment]
Moin Christian, 

danke für das nette Feedback!

ich habe es mir gerade nochmal mit einem Kollegen angeguckt und wir finden leider keinen Fehler. 
Die drei if-Abfragen testen im Prinzip ob (wx - mod - valx) positiv ist: 
```
	wx - mod - valx > 0		|| + mod
<=>	wx - valx 	> mod 		|| + valx
<=>	wx 		> valx + mod
```
Kannst du den Fehler anders beschreiben?

Viele Grüße
Tobias

**Comment by cgruenwied** [comment]
Hallo Tobias,

du hast völlig recht - da sind if-Abfragen vorher. Sorry, wenn ich "die Pferde scheu" gemacht habe, das ist schon richtig so. Bleibt nur noch das Lob!

Viele Grüße,

Christian
